# Generated by Django 3.2.5 on 2021-07-23 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='text')),
                ('value', models.CharField(blank=True, max_length=50, null=True, verbose_name='value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('text', models.TextField(max_length=500, verbose_name='text')),
                ('is_required', models.BooleanField(default=True, verbose_name='is required')),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('multiline_text', 'Multiline text'), ('checkbox', 'Checkbox'), ('radio', 'Radio')], max_length=30, verbose_name='question type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=30, verbose_name='status')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='default value')),
                ('placeholder', models.TextField(blank=True, null=True, verbose_name='placeholder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
